# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: Lottery
# Author: https://www.mc-market.org/members/89497/
# Description: Simple plugin for players to participate in an in-game lottery.
# Dependencies:
#   -> PLJRApi
#   -> PlaceholderAPI<Optional> (https://www.spigotmc.org/resources/placeholderapi.6245/)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##################\
# Settings Setup #############################################################\
################## Here, you can enable or disable functions of this plugin. # \
                 #############################################################  \
settings:
  bungee: false #-> Should we use bungee functions?
  multiple-tickets: true #-> Should players be able to buy multiple tickets?
  confirmation: true #-> Should we ask players for confirmation, when buying tickets?
  broadcast-chat: true #-> Should we broadcast in chat?
  broadcast-actionbar: true #-> Should we broadcast in actionbar?
  broadcast-title: true #-> Should we broadcast in Title?
  start-on-startup: true #-> Should we start the lottery on server startup?
  restart-on-end: true #-> Should we start a new lottery after ending one?
  cost: 100 #-> How much should 1 ticket cost?
  countdown: 500 #-> How long should it take for a lottery to end? (In seconds)
  cache-players: true # Should we save player data in memory? (false = loading on each join)
#|--------------------------------------------------------------------------------------------------------------------|#