name: Lottery
version: ${project.version}
main: me.pljr.lottery.Lottery
api-version: 1.13
authors: [9hx]
description: Simple plugin for players to participate in an in-game lottery.
depend: [PLJRApi]
softdepend: [Vault]
commands:
  lottery:
    description: Main command for lottery.
  alottery:
    description: Admin command for lottery.
